### ISSUE TITLE
Add profile photo

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status#36]
https://github.com/status-im/status/issues/4

## Add profile photo
Source: Roadmap planning workshop [item status-im/status-react#48](https://docs.google.com/spreadsheets/d/1e3zXnLMbMJ6XNkKXMTe3u5oBgn4-X_wdkrvpTSt-1ag/edit#gid=0&range=A19) and [Discuss](https://discuss.status.im/t/username-and-profile-picture-not-linked-to-ens/1755) 

### User stories
- As a user, I want to define a name and profile photo to display my contacts without having to change the ETH address, so that it is inviting to non-technical users and cryptocurrency enthusiasts and even inexperienced with encryption.

#### Use cases
- View photo in Profile
- View photo in other user profile
- View photo in chat
- View photo for 1:1 chat in chat list
- View photo in notification
- Update photo when registering ENS, in Profile or both (TBD)
    - Select photo from gallery
    - Take photo
    - Crop photo
    - Show photo is updating (if ca >8 sec)

[Designs](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=5662%3A233)

---

### Progress Summary

- Profile photo
  - specs
    - [Draft v1](https://notes.status.im/CQ-GGYmAR3aM8qUABgedWg?both)
    - [Draft v2](https://notes.status.im/oUChlPB3Q2aUPLYBSjq6MQ?both)
  - [Vector image research](https://notes.status.im/0MWyryTPQleMWe31K0L7gg?both)
    - Vector images are useful for organisation that want a custom icon associated with their chat key, but an avatar is not an appropriate representation of the organisation.
- Profile avatar
  - [Initial concept](https://notes.status.im/vk29m0ZjT1WClNR1BR8msg?both)
  - [Concept presentation](https://docs.google.com/presentation/d/1rP9YaeBYPqXgLVX1jkY1cFy1kExzg535YKo1VI7oSQk/edit#slide=id.p)
  - [Proof of concept lib](https://github.com/status-im/avatar)

**Comment by errorists** [comment]
lol, fuck logic amirite? 😅 let's do without cropping then. for compression quality, I think we could also max it at 80%, as at this small size going up will yield increasingly diminishing returns. thanks man, the baby elephant is cute.

**Comment by Samyoul** [comment]
The results for 240px images.

Basically the same but the margins of difference are much larger.

It think the reason for this counter intuitive result is because the compression algorithms seek to keep the image as close to the original as possible by matching colours, and adding none congruent black shapes makes it harder to do this. Also a circle is an unhelpful shape, it basically intersects with lots of the compression chunks and in most cases increases the work required to compress the image.

I tried just adding a black square in the corner and that did consistently and significantly reduce the file size. Not very nice to look at though.

<details>
<summary>See the 240px images</summary>

| Image | Properties | Size (px^2) | Image Quality (%) | Size (bytes) |
| :---: | ---------- | ----------: | ----------------: | -----------: |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/elephant_s-240_q-60.jpg) |  | 240 | 60 | 10,224 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/elephant_s-240_q-60_pre-render-circle-crop.jpg) | pre-render circle crop | 240 | 60 | 10,295 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/elephant_s-240_q-60_post-render-circle-crop.jpg) | post-render circle crop | 240 | 60 | 10,248 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/frog_s-240_q-80.jpg) |  | 240 | 80 | 9,138 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/frog_s-240_q-80_pre-render-circle-crop.jpg) | pre-render circle crop | 240 | 80 | 9,519 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/frog_s-240_q-80_post-render-circle-crop.jpg) | post-render circle crop | 240 | 80 | 9,499 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/goat_s-240_q-80.jpg) |  | 240 | 80 | 9,228 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/goat_s-240_q-80_pre-render-circle-crop.jpg) | pre-render circle crop | 240 | 80 | 10,267 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/goat_s-240_q-80_post-render-circle-crop.jpg) | post-render circle crop | 240 | 80 | 10,269 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/mars_s-240_q-90.jpg) |  | 240 | 90 | 8,218 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/mars_s-240_q-90_pre-render-circle-crop.jpg) | pre-render circle crop | 240 | 90 | 8,209 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/mars_s-240_q-90_post-render-circle-crop.jpg) | post-render circle crop | 240 | 90 | 8,212 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/psychedelic_s-240_q-30.jpg) |  | 240 | 30 | 10,419 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/psychedelic_s-240_q-30_pre-render-circle-crop.jpg) | pre-render circle crop | 240 | 30 | 9,413 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/psychedelic_s-240_q-30_post-render-circle-crop.jpg) | post-render circle crop | 240 | 30 | 9,406 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/rainbow_s-240_q-70.jpg) |  | 240 | 70 | 8,793 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/rainbow_s-240_q-70_pre-render-circle-crop.jpg) | pre-render circle crop | 240 | 70 | 8,931 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/rainbow_s-240_q-70_post-render-circle-crop.jpg) | post-render circle crop | 240 | 70 | 8,938 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/romanian-flag_s-240_q-100.jpg) |  | 240 | 100 | 3,711 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/romanian-flag_s-240_q-100_pre-render-circle-crop.jpg) | pre-render circle crop | 240 | 100 | 14,517 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/romanian-flag_s-240_q-100_post-render-circle-crop.jpg) | post-render circle crop | 240 | 100 | 14,535 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/tormund_s-240_q-60.jpg) |  | 240 | 60 | 10,274 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/tormund_s-240_q-60_pre-render-circle-crop.jpg) | pre-render circle crop | 240 | 60 | 9,560 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/tormund_s-240_q-60_post-render-circle-crop.jpg) | post-render circle crop | 240 | 60 | 9,511 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/woman_s-240_q-90.jpg) |  | 240 | 90 | 9,223 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/woman_s-240_q-90_pre-render-circle-crop.jpg) | pre-render circle crop | 240 | 90 | 7,754 |
| ![](https://raw.githubusercontent.com/status-im/image-resizer/7e2348d2323eab12fc2dd90938560624ff865ce9/images/woman_s-240_q-90_post-render-circle-crop.jpg) | post-render circle crop | 240 | 90 | 7,726 |

</details>

**Comment by hesterbruikman** [comment]
Closing as this has been implemented
